name: seaiceobs
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - netcdf4
  - pandas
  - matplotlib
  - cftime
  - cmocean
  - nc-time-axis

